# Additional configuration for production

admin:
    # Nur innerhalb der VZG zugänglich
    ips:
        - 195.37.139.0/24
        - 193.174.240.0/24 

plugins:
    Database:
        driver: 'SQLite'
        database: '/home/picamodbot/data/picamodbot.sqlite'

behind_proxy: true
