# Additional configuration for production

admin:
    # Nur innerhalb der VZG zugänglich
    ips:
        - 195.37.139/255
        - 193.174.240/255 

plugins:
    Database:
        driver: 'SQLite'
        database: '~/data/picamodbot.sqlite'

