appname: "picamodbot"
layout: "main"
charset: "UTF-8"

template: "template_toolkit"
engines:
    template_toolkit:
        encoding:  'utf8'
        start_tag: '[%'
        end_tag:   '%]'

plugins:
    Database:
        driver: 'SQLite'
        database: 'picamodbot.sqlite'

# add access tokens in access_tokens.yml

