requires 'Plack', '1.0';

requires 'Plack::Middleware::TemplateToolkit', '0.26';
requires 'Plack::Middleware::Negotiate', '0.06';
requires 'Plack::Middleware::XForwardedFor', '0';

requires 'Test::JSON::Entails', '0.2';

requires 'PICA::Record', '0.584';
